name: AI News Scraper

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点运行

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ai_news.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update AI news data"
            git push
          fi